### ISSUE TITLE
Error on `yarn start`

### ISSUE THREAD

**Issue by okwme** [ChainSafe/ethermint-deploy#3]
Seem to have a running version of `emintd` running but `yarn start` fails with this error:
```sh
> yarn start
yarn run v1.16.0
$ node ./web3/deploy_contract.js
Compiling contract code...
{ currentAccounts: [ '0x22FD28bAfe8D4a72fda7a59b5836f12Cf1FA4374' ] }
Unlocked account address: 	 0x22FD28bAfe8D4a72fda7a59b5836f12Cf1FA4374
Deploying contract...
Error: The transaction receipt didn't contain a contract address.
    at /home/billy/GitHub.com/chainsafe/ethermint-deploy/node_modules/web3-core-method/src/index.js:343:33
    at process._tickCallback (internal/process/next_tick.js:68:7)
Done in 3.71s.
```

**Comment by austinabell** [comment]
can't replicate, can you give any more details if this is still an issue?

**Comment by okwme** [comment]
no longer the case with latest version, not sure what changed tho
